// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_structured_atl_cpp
List simulate_structured_atl_cpp(List cfg);
RcppExport SEXP _Reservoir_simulate_structured_atl_cpp(SEXP cfgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cfg(cfgSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_structured_atl_cpp(cfg));
    return rcpp_result_gen;
END_RCPP
}
// simulate_vectorborne_atl_cpp
List simulate_vectorborne_atl_cpp(List cfg);
RcppExport SEXP _Reservoir_simulate_vectorborne_atl_cpp(SEXP cfgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cfg(cfgSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_vectorborne_atl_cpp(cfg));
    return rcpp_result_gen;
END_RCPP
}
// simulate_env_atl_cpp
List simulate_env_atl_cpp(List cfg);
RcppExport SEXP _Reservoir_simulate_env_atl_cpp(SEXP cfgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cfg(cfgSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_env_atl_cpp(cfg));
    return rcpp_result_gen;
END_RCPP
}


// apply_reporting_delays_cpp
NumericVector apply_reporting_delays_cpp(NumericVector cases, NumericVector progress, int init_max_delay, int final_max_delay, double gamma_shape, double gamma_rate, double steepness, double midpoint);
RcppExport SEXP _Reservoir_apply_reporting_delays_cpp(SEXP casesSEXP, SEXP progressSEXP, SEXP init_max_delaySEXP, SEXP final_max_delaySEXP, SEXP gamma_shapeSEXP, SEXP gamma_rateSEXP, SEXP steepnessSEXP, SEXP midpointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cases(casesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type init_max_delay(init_max_delaySEXP);
    Rcpp::traits::input_parameter< int >::type final_max_delay(final_max_delaySEXP);
    Rcpp::traits::input_parameter< double >::type gamma_shape(gamma_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_rate(gamma_rateSEXP);
    Rcpp::traits::input_parameter< double >::type steepness(steepnessSEXP);
    Rcpp::traits::input_parameter< double >::type midpoint(midpointSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_reporting_delays_cpp(cases, progress, init_max_delay, final_max_delay, gamma_shape, gamma_rate, steepness, midpoint));
    return rcpp_result_gen;
END_RCPP
}
// hospital_occupancy_cpp
IntegerVector hospital_occupancy_cpp(IntegerVector daily_hosp, int avg_los);
RcppExport SEXP _Reservoir_hospital_occupancy_cpp(SEXP daily_hospSEXP, SEXP avg_losSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type daily_hosp(daily_hospSEXP);
    Rcpp::traits::input_parameter< int >::type avg_los(avg_losSEXP);
    rcpp_result_gen = Rcpp::wrap(hospital_occupancy_cpp(daily_hosp, avg_los));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Reservoir_apply_reporting_delays_cpp", (DL_FUNC) &_Reservoir_apply_reporting_delays_cpp, 8},
    {"_Reservoir_hospital_occupancy_cpp", (DL_FUNC) &_Reservoir_hospital_occupancy_cpp, 2},
    {"_Reservoir_simulate_structured_atl_cpp",  (DL_FUNC) &_Reservoir_simulate_structured_atl_cpp,  1},
    {"_Reservoir_simulate_vectorborne_atl_cpp", (DL_FUNC) &_Reservoir_simulate_vectorborne_atl_cpp, 1},
    {"_Reservoir_simulate_env_atl_cpp",         (DL_FUNC) &_Reservoir_simulate_env_atl_cpp,         1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Reservoir(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
