# Generated by using Rcpp::compileAttributes() -> do not edit by hand

simulate_structured_atl_cpp <- function(cfg) {
    .Call(`_Reservoir_simulate_structured_atl_cpp`, cfg)
}

simulate_vectorborne_atl_cpp <- function(cfg) {
    .Call(`_Reservoir_simulate_vectorborne_atl_cpp`, cfg)
}

simulate_env_atl_cpp <- function(cfg) {
    .Call(`_Reservoir_simulate_env_atl_cpp`, cfg)
}

apply_reporting_delays_cpp <- function(cases, progress, init_max_delay, final_max_delay, gamma_shape, gamma_rate, steepness, midpoint) {
    .Call(`_Reservoir_apply_reporting_delays_cpp`, cases, progress, init_max_delay, final_max_delay, gamma_shape, gamma_rate, steepness, midpoint)
}

hospital_occupancy_cpp <- function(daily_hosp, avg_los) {
    .Call(`_Reservoir_hospital_occupancy_cpp`, daily_hosp, avg_los)
}
